name: CI Development

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '0 0 * * 0'  # Ejecutar cada domingo a medianoche para reentrenamiento semanal

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest --cov=app tests/

  train_model:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python -m app.model.train

      - name: Upload trained model
        uses: actions/upload-artifact@v2
        with:
          name: diabetes-model
          path: models/diabetes_model.pkl

  build_docker:
    runs-on: ubuntu-latest
    needs: [test, train_model]
    steps:
      - uses: actions/checkout@v2

      - name: Download trained model
        uses: actions/download-artifact@v2
        with:
          name: diabetes-model
          path: models/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: diabetes-api:develop

      - name: Test Docker image
        run: |
          docker run --name diabetes-api -d -p 8000:8000 diabetes-api:develop
          sleep 10
          curl -f http://localhost:8000/health || exit 1