name: CI Development

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '0 0 * * 0'  # Ejecutar cada domingo a medianoche para reentrenamiento semanal

jobs:
  development_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

      - name: Train model
        run: |
          python -m app.model.train

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true  # Cargar la imagen en Docker localmente
          tags: diabetes-api:develop

      - name: List Docker images
        run: |
          docker images

      - name: Verify Docker build
        run: |
          echo "Verificando que la imagen Docker se construyó correctamente"
          # Esta verificación evita probar ejecutar la imagen, lo que puede causar problemas en algunos entornos CI
          docker image inspect diabetes-api:develop > /dev/null
          echo "La imagen Docker se construyó correctamente"