name: CI/CD Staging

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest --cov=app tests/

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Download model from develop
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: develop.yml
          workflow_conclusion: success
          name: diabetes-model
          path: models/
          repo: ${{ github.repository }}

      - name: Verify downloaded model
        run: |
          ls -l models/
          file models/diabetes_model.pkl || echo "Model file not found"

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: diabetes-model
          path: models/diabetes_model.pkl
          retention-days: 3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-api:staging

  deploy_staging:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to staging environment
        run: |
          echo "Simulando despliegue a entorno de staging..."
          echo "Despliegue completado en entorno de staging."